config/routes.rb
Texter::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :users
  resources :recipients
  root to: "texts#index"
  resources :texts
    resources :recipients
end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
  has_and_belongs_to_many :texts
 end

app/models/text.rb
class Text < ActiveRecord::Base
  before_create :send_text
  has_and_belongs_to_many :recipients
  accepts_nested_attributes_for :recipients

private

 def send_text
    recipient_ids.each do |recipient_id|
      begin
      recipient = Recipient.find(recipient_id)

      response = RestClient::Request.new(
        :method => :post,
        :url => "https://api.twilio.com/2010-04-01/Accounts/#{ENV['TWILIO_ACCOUNT_SID']}/Messages.json",
        :user => ENV['TWILIO_ACCOUNT_SID'],
        :password => ENV['TWILIO_AUTH_TOKEN'],
        :payload => { :Body => body,
                      :To => recipient.phone,
                      :From => from }
      ).execute

      rescue RestClient::BadRequest => error
        message = JSON.parse(error.response)['message']
        errors.add(:base, message)
        false
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

   def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:name, :email,:phone, :number, :password, :password_confirmation)
    end
  end
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController

  def index
    @recipients = Recipient.all
  end

  def new
    @recipient = Recipient.new
  end

  def create
    @recipient = Recipient.new(recipients_params)
    if @recipient.save
      redirect_to recipients_url
    else
      render 'new'
    end
  end

private

  def recipients_params
    params.require(:recipient).permit(:name, :phone, :user_id, :recipient_ids => [])
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController

  def index
    @texts = Text.all
  end

  def show
    @text = Text.find(params[:id])
  end

  def new
    @text = Text.new
    @recipient = Recipient.new
    @recipients = Recipient.all
    @text.recipients.build
  end



  def create
    @text = Text.new(texts_params)
    if @text.save
      flash[:notice] = "text sent!"
      redirect_to root_url
    else
      render 'new'
    end
  end

  # def destroy
  #   @text = Text.find(params[:id])
  #   @text.destroy
  #   redirect_to(root_path)
  # end

private

  def texts_params
    params.require(:text).permit(:to, :from, :body, :text_id, :text_ids, :recipient_ids => [])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/new.html.erb
<h2> Add a new person to the text list </h2>

<%= form_for @address do |f| %>
    <div class="form-group">
      <%= f.label :Name %></br>
      <%= f.text_field :name %>
    </div>
    <div class="form-group">
    <%= f.hidden_field :user_id, :value => current_user.id %>
    </div>
    <div class="form-group">
      <%= f.label :phonenumber %>
      <%= f.text_field :phone %>
    </div>
    <div class="form-group">
      <%= f.submit(:class => "btn btn-primary") %>
    </div>
    <% end %>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="error_messages">
    <h2>Please correct errors:</h2>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title)+" | Texter " : "Texter" %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="navbar navbar-default navbar-fixed-top">
    <%= link_to "PDX Silent Disco", root_url, class: "navbar-text pull-left" %>
    <div class="navbar-text">
      <div class="center-bold">
        <%= flash[:notice] %>
        <%= flash[:alert] %>
      </div>
    </div>
    <% if current_user %>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Send New Text", new_text_path %> </a></li>
        <li class="active"><%= link_to 'Edit profile', edit_user_registration_path %> </li>

    </div>
      </ul>

     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => "btn btn-primary" %></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <div class="navbar-text">
            <li><h7>Logged in as <%= current_user.email %></h7></li>
          </div>
        </ul>
    <% else %>
      <%= link_to "Log In", new_user_session_path, class: "navbar-text pull-right" %>
      <%= link_to "Sign Up", new_user_registration_path, class: "navbar-text pull-right" %>
    <% end %>
  </div>

  <div id="main">
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/recipients/index.html.erb
<h2> These people are plugged in: </h2>

<ul>
<% @recipients.each do |recipient| %>
<li> <%= recipient.name %> </li>
<% end %>

</ul>

app/views/recipients/new.html.erb
<h2> Add a new person to the text list </h2>

<%= form_for @recipient do |f| %>
    <div class="form-group">
      <%= f.label :Name %></br>
      <%= f.text_field :name %>
    </div>
    <div class="form-group">
    <%= f.hidden_field :user_id, :value => current_user.id %>
    </div>
    <div class="form-group">
      <%= f.label :phonenumber %>
      <%= f.text_field :phone %>
    </div>
    <div class="form-group">
      <%= f.submit(:class => "btn btn-primary") %>
    </div>
    <% end %>
</div>

app/views/texts/index.html.erb
<h2> Welcome to Texter! </h2>

app/views/texts/new.html.erb
<h2> Send a new text!</h2>
<%= form_for @text, :remote => true do |f| %>
<div class="form-group">
    <% Recipient.all.each do |recipient| %>
        <%= check_box_tag "text[recipient_ids][]", recipient.id, @text.recipient_ids.include?(recipient.id), id: dom_id(recipient) %>
        <%= label_tag dom_id(recipient), recipient.name %>
    <% end %>

    <div class="form-group">
    <%= f.hidden_field :from, :value => '5034054073' %>
    </div>
    <div class="form-group">
      <%= f.label :Text_Message %>
      <%= f.text_field :body, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit(:class => "btn btn-primary") %>
    </div>
    <% end %>
</div>

app/views/users/index.html.erb
<h2> Welcome to Texter! </h2>